services:
  symfony-preprod:
    image: symfony-php-api:preprod
    container_name: preprod-api_sf
    build:
      context: ./
    networks:
      - api-preprod
      - traefik-realt
    volumes:
      - ./logs/symfony:/var/www/html/var/log:cached
      - ./logs/nginx:/var/log/nginx:cached
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-preprod.rule=Host(`api.preprod.realtoken.community`)"
    restart: always

  db-preprod:
    image: mysql:5.7
    container_name: preprod-api_db
    networks:
      - api-preprod
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
    restart: always

  adminer-preprod:
    image: adminer
    container_name: preprod-api_adminer
    ports:
      - "18081:8080"
    networks:
      - api-preprod
    restart: always

networks:
  api-preprod:
  traefik-realt:
    external: true
