services:
  symfony-prod:
    image: realt-api:1.0
    container_name: prod-api_php-sf
    build:
      context: ./
    networks:
      - api-prod
      - traefik-realt
    volumes:
      - ./logs/symfony:/var/www/html/var/log:cached
      - ./logs/nginx:/var/log/nginx:cached
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-prod.rule=Host(`api.realtoken.community`)"
      - "traefik.http.services.api-prod.loadbalancer.server.port=80"
    restart: always

  db-prod:
    image: mysql:5.7
    container_name: prod-api_php-db
    networks:
      - api-prod
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
    restart: always

  adminer-prod:
    image: adminer
    container_name: prod-api_php-adminer
    ports:
      - "18080:8080"
    networks:
      - api-prod
    restart: always

networks:
  api-prod:
  traefik-realt:
    external: true
