version: '3.2'

services:
  symfony:
    image: realt-api:preprod
    container_name: realtapi_preprod-sf
    build:
      context: ./
    ports:
      - "9081:80"
    networks:
      - realtapipreprod
      - traefik-realt
    volumes:
      - ./logs/symfony:/var/www/html/var/log:cached
      - ./logs/nginx:/var/log/nginx:cached
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sf-realt-api-preprod.rule=Host(`api.preprod.realt.community`)"
      - "traefik.http.routers.sf-realt-api-preprod.entrypoints=websecure"
    restart: always

  db:
    image: mysql:5.7
    container_name: realtapi_preprod-db
    ports:
      - "3307:3306"
    networks:
      - realtapipreprod
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
    restart: always

  adminer:
    image: adminer
    container_name: realtapi_preprod-adminer
    ports:
      - "18081:8080"
    networks:
      - realtapipreprod
    restart: always

networks:
  realtapipreprod:
  traefik-realt:
    external: true