version: '3.2'

services:
  php-api_symfony:
    image: registry.realt.community/symfony-php-api-realt:${DOCKER_BRANCH}
    container_name: ${DOCKER_BRANCH}-php-api_symfony
    build:
      context: ./
    ports:
      - "9082:80"
    networks:
      - realt
      - traefik-realt
    volumes:
      - ./logs/symfony:/var/www/html/var/log:cached
      - ./logs/nginx:/var/log/nginx:cached
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sf-realt-api-${DOCKER_BRANCH}.rule=Host(`api.${DOCKER_BRANCH}.realt.community`)"
      - "traefik.http.routers.sf-realt-api-${DOCKER_BRANCH}.entrypoints=websecure"
    restart: always

  php-api_db:
    image: mysql:5.7
    container_name: ${DOCKER_BRANCH}-php-api_db
    ports:
      - "3308:3306"
    networks:
      - realt
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
    restart: always

  php-api_adminer:
    image: adminer
    container_name: ${DOCKER_BRANCH}-php-api_adminer
    ports:
      - "18082:8080"
    networks:
      - realt
    restart: always

networks:
  realt:
  traefik-realt:
    external: true
