version: '3.2'

services:
  alpha-php-api_symfony:
    image: registry.realt.community/symfony-php-api-realt:alpha
    container_name: alpha-php-api_symfony
    build:
      context: ./
    ports:
      - "9081:80"
    networks:
      - alpha-php-api-realt
      - traefik-realt
    volumes:
      - ./logs/symfony:/var/www/html/var/log:cached
      - ./logs/nginx:/var/log/nginx:cached
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sf-realt-api-alpha.rule=Host(`api.alpha.realt.community`)"
      - "traefik.http.routers.sf-realt-api-alpha.entrypoints=websecure"
    restart: always

  alpha-php-api_db:
    image: mysql:5.7
    container_name: registry.realt.community/db-php-api-realt:alpha
    ports:
      - "3307:3306"
    networks:
      - alpha-php-api-realt
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
    restart: always

  alpha-php-api_adminer:
    image: adminer
    container_name: registry.realt.community/adminer-php-api-realt:alpha
    ports:
      - "18081:8080"
    networks:
      - alpha-php-api-realt
    restart: always

networks:
  alpha-php-api-realt:
  traefik-realt:
    external: true
