services:
  symfony-prod:
    image: realt-api:1.0
    container_name: realtapi_prod-sf
    build:
      context: ./
    networks:
      - realtapiprod
      - traefik-realt
    volumes:
      - ./logs/symfony:/var/www/html/var/log:cached
      - ./logs/nginx:/var/log/nginx:cached
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sf-realt-api-prod.rule=Host(`api.realtoken.community`)"
    restart: always

  db-prod:
    image: mysql:5.7
    container_name: realtapi_prod-db
    networks:
      - realtapiprod
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
    restart: always

  adminer-prod:
    image: adminer
    container_name: realtapi_prod-adminer
    ports:
      - "18080:8080"
    networks:
      - realtapiprod
    restart: always

networks:
  realtapiprod:
  traefik-realt:
    external: true
