app.swagger_v1:
    path: /
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger_v2:
    path: /doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.redocly }

app.swagger_doc:
    path: /doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }
