version: 2

orbs:
  discord: antonioned/discord@0.1.0

jobs:
  build:
    docker:
#      - image: sigri44/circleci-php-ruby-capistrano
      - image: circleci/buildpack-deps:stretch
        environment:
          IMAGE_NAME: silarhi/symfony-docker-ci
    steps:
      - checkout

  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "20:00:72:01:07:09:68:c9:78:df:ee:54:2e:72:5a:c8"
      - run:
          name: "Deploy image to staging"
          command: |
            ssh root@${VPS_REALT_IP} -p ${VPS_REALT_PORT} "cd ${VPS_REALT_PATH} && ./deploy.sh"

  webhook:
    machine:
      enabled: true
    steps:
      - discord/status:
          fail_only: false
          success_message: "**${CIRCLE_USERNAME}** deployed successfully RealT API to PreProd."
          failure_message: "**${CIRCLE_USERNAME}**'s build: **${CIRCLE_JOB}** failed."
          webhook: "${DISCORD_STATUS_WEBHOOK}"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: preprod
      - webhook:
          requires:
            - deploy