version: 2.1

orbs:
  discord: antonioned/discord@0.1.0

jobs:
  build:
    docker:
#      - image: sigri44/circleci-php-ruby-capistrano
      - image: cimg/base:current
        environment:
          IMAGE_NAME: silarhi/symfony-docker-ci
    steps:
      - checkout
      - run:
          name: "What branch am I on now?"
          command: echo $CIRCLE_BRANCH

  deploy:
    machine:
      image: ubuntu-2004:current
    steps:
      - add_ssh_keys:
          fingerprints:
            - "20:00:72:01:07:09:68:c9:78:df:ee:54:2e:72:5a:c8"
      - run: echo ${VPS_REALT_HOST}
      - run:
          name: "Deploy image to staging"
          command:
#            echo ${VPS_REALT_HOST}
#            echo $VPS_REALT_HOST
#            ssh ${VPS_REALT_USER}@${VPS_REALT_HOST} "ls -lah"
#            ssh ${VPS_REALT_USER}@${VPS_REALT_IP} "ls -lah"
#            ssh ${VPS_REALT_USER}@${VPS_REALT_HOST} -p ${VPS_REALT_PORT} "ls -lah"
#            ssh ${VPS_REALT_USER}@${VPS_REALT_IP} -p ${VPS_REALT_PORT} "ls -lah"
#            ssh ${VPS_REALT_USER}@${VPS_REALT_IP} -p ${VPS_REALT_PORT} "cd ${VPS_REALT_PATH} && ./deploy.sh"
            ssh realt@149.202.145.112 -p 2222 "cd /home/realt/docker/api/preprod && ./current/.circleci/continous_deployment.sh"

  webhook:
    machine:
      enabled: true
    steps:
      - discord/status:
          fail_only: false
          success_message: "**${CIRCLE_USERNAME}** deployed successfully RealT API to PreProd."
          failure_message: "**${CIRCLE_USERNAME}**'s build: **${CIRCLE_JOB}** failed."
          webhook: "${DISCORD_STATUS_WEBHOOK}"

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - preprod
                - circleci
      - webhook:
          requires:
            - deploy
