version: 2.1
orbs:
  discord: antonioned/discord@0.1.0

jobs:
  build:
    docker:
      - image: circleci/php:7.4
#      - image: circleci/ruby:2.7.2
#      - image: yoant/circleci-node-ruby
#      - image: sigri44/circleci-php-ruby-capistrano

    steps:
      - checkout

      - run: sudo apt update
      - run: sudo apt install ruby ruby-dev
      - run: sudo docker-php-ext-install zip

      # Install Bundler & Capistrano
      - run: sudo gem install bundler
      - run: sudo gem install capistrano capistrano-ext capistrano-multiconfig
      - run: sudo bundle install

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-

      - run:
          name: "Create Environment file"
          command: mv .env.circleci .env
      - run:
          name: "Install Dependencies"
          command : composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run:
          name: "Run web server"
          #command: php bin/console server:run
          command: symfony server:start
          background: true

#       Database
#      - run: touch storage/testing.sqlite
#      - run: php bin/console doctrine:migrations:migrate
#
#       Run tests with phpunit
#      - run:
#          name: "Run tests"
#          command: composer test

      - add_ssh_keys:
          fingerprints:
            - "20:00:72:01:07:09:68:c9:78:df:ee:54:2e:72:5a:c8"

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              bundle exec cap production deploy
            fi

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "circleci-project-setup" ]; then
              bundle exec cap staging deploy
#              cap staging deploy
            fi

      - discord/status:
          fail_only: false
          success_message: "**${CIRCLE_USERNAME}** deployed successfully RealT API to PreProd."
          failure_message: "**${CIRCLE_USERNAME}**'s build: **${CIRCLE_JOB}** failed."
          webhook: "${DISCORD_STATUS_WEBHOOK}"
