name: Connect & Deploy

on:
  push:
    branches:
      - circleci


jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: ssh key passphrase
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.KURTISONELAB_SSH_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KURTISONELAB_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          passphrase: ${{ secrets.KURTISONELAB_SSH_KNOWN_HOST }}
          script: |
            whoami
            ls -al

      - name: "Deploy Capistrano pipeline"
        run: ssh ${{ secrets.KURTISONELAB_SSH_USER }}@${{ secrets.KURTISONELAB_SSH_HOST }} -p ${{ secrets.SSH_PORT }} "cd ${WORKING_DIR}/current && ls -al"
        #Host key verification failed.

