name: CI

on:
  push:
    branches:
      - circleci


jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Deploy Capistrano pipeline"
        # Need to fix user@host:port, use variables
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -p ${{ secrets.SSH_PORT }} "cd ${WORKING_DIR}/current && cap symfony:realtapi:staging deploy --trace"