name: Connect & Deploy

on:
  push:
    branches:
      - circleci


jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      #- name: Checkout
      #  uses: actions/checkout@v3
      #- name: ssh key passphrase
      #  uses: appleboy/ssh-action@master
      #  with:
      #    host: ${{ secrets.KURTEST_REALT_HOST }}
      #    username: ${{ secrets.KURTEST_REALT_USER }}
      #    key: ${{ secrets.KURTEST_REALT_SSH_KEY }}
      #    port: ${{ secrets.SSH_PORT }}
        # passphrase: ${{ secrets.KURTISONELAB_SSH_KNOWN_HOST }}
      #    script: bundle exec cap staging deploy

      - name: "Setup Ruby"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.1
          bundler-cache: true
      - name: "Deploy Capistrano pipeline"
        uses: miloserdow/capistrano-deploy@master
        with:
          target: staging
          enc_rsa_key_pth: config/deploy_id_ed25519_enc
          deploy_key: ${{ secrets.KURTEST_CAPISTRANO_PASSWORD }}

      #-
      #  name: Set up QEMU
      #  uses: docker/setup-qemu-action@v2
      #-
      #  name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v2
      #-
      #  name: Build and push
      #  uses: docker/build-push-action@v3