name: Connect & Deploy

on:
  push:
    branches:
      - circleci


jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      #- name: ssh key passphrase
      #  uses: appleboy/ssh-action@master
      #  with:
      #    host: ${{ secrets.KURTISONELAB_SSH_HOST }}
      #    username: ${{ secrets.KURTISONELAB_SSH_USER }}
      #    key: ${{ secrets.KURTISONELAB_SSH_KEY }}
      #   port: ${{ secrets.SSH_PORT }}
      #    passphrase: ${{ secrets.KURTISONELAB_SSH_KNOWN_HOST }}
      #    script: |
      #      cd ${WORKING_DIR}/current && ls -al

      - name: "Setup Ruby"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.1
          bundler-cache: true
      - name: "Deploy Capistrano pipeline"
        uses: miloserdow/capistrano-deploy@master
        with:
          target: circleci
